[theme]

# Primary accent for interactive elements
primaryColor = '#476fe6ff'

# Background color for the main content area
backgroundColor = '#09152bff'

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = '#4d0978ff'

# Color used for almost all text
textColor = '#FFFFFF'

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace) 
# Default: "sans serif"
font = "sans serif"